### ISSUE TITLE
SSL on main client?

### ISSUE THREAD

**Issue by probablypablito** [Macro-Deck-App/Macro-Deck-Web-Client#17]
I noticed there's no SSL on web.macrodeck.org.

Could this be added, or if not then instructs on how to self-host the web client? I wouldn't want anyone on my local network to be able to sniff the http traffic if it contains sensitive info.

**Comment by SuchByte** [comment]
There is no SSL certificate because currently Macro Deck does not support secure websockets and a SSL secured web app cannot access a non secured WebSocket server but you don't need to worry. The web client runs only on your local machine and does not send any data to a web server outside your network. Also over the connection is no sensitive data transmitted which could be sniffed.

If you still want to self-host the client, you can setup any web server (Node, Apache, Nginx...)
